### ISSUE TITLE
ImportError: cannot import name 'logcurr_vidgear_ver'

### ISSUE THREAD

**Issue by gavanfantom** [fieldOfView/WLED-video#2]
```
python3 wledvideo.py --host xxx.xxx.xxx.xxx file.mp4
Traceback (most recent call last):
  File "wledvideo.py", line 10, in <module>
    import src.loopablecamgear as loopablecamgear
  File "/path/to/WLED-video/src/loopablecamgear.py", line 29, in <module>
    from vidgear.gears.helper import (
ImportError: cannot import name 'logcurr_vidgear_ver'
```

This is on a rather old Ubuntu Studio (18.04) with Python3, and after loading the specified requirements from requirements.txt with pip.

**Comment by fieldOfView** [comment]
Thanks for the issue (and for letting me play with your display). I'll look into it.

**Comment by fieldOfView** [comment]
What is the output of `pip3 list | grep vidgear`?

If the vidgear module version is older than 0.3.2, please try `pip3 install --upgrade vidgear`

**Comment by gavanfantom** [comment]
Vidgear is 0.2.4 is what I have. Trying to ugprade it with pip yields the same version.

It seems that vidgear 0.3.2 requires Python >= 3.8. I have Python 3.6.9. Perhaps that's the problem?

**Comment by fieldOfView** [comment]
That's probably it. Python 3.6 has reached EOL Dec 2021 and is no longer receiving security updates.
